/* Generated by powerful Codeforces Tool
 * Author: Kenshin2438
 * Time: 2021-11-22 20:46:15
**/
 
#include <cstdio>
#include <cstring>
#include <cmath>
#include <ctime>
#include <cassert>
 
#include <algorithm>
#include <random>
#include <chrono>
#include <iostream>
#include <functional>
#include <bitset>
#include <vector>
#include <string>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <unordered_map>
 
#define PII pair<int, int>
#define vec vector
#define str string
#define fi first
#define se second
#define pb push_back
#define all(a) a.begin(), a.end()
using namespace std;
 
typedef long long ll;
typedef unsigned long long ull;
 
const int mod = 1e9 + 7;
const int N = 1e6 + 10;
const int inf = 0x3f3f3f3f;
const ll  INF = 1e18;
const double eps = 1e-8;
 
int T;
 
str s;
int q, n, ans[N], len;
 
int main() {
  ios_base::sync_with_stdio(false), cin.tie(nullptr), cout.tie(nullptr);
  cin >> s >> q;
  n = s.length(), len = 1;
  ull lsh = 0, rsh = 0, base = 131, tmp = 1;
  for (int i = 0, j = n - 1; i <= j; i++, j--, len++) {
    lsh = lsh * base + (s[i] - 'a' + 1);
    rsh = rsh + tmp * (s[j] - 'a' + 1), tmp *= base;
    ans[len] = (int) (lsh == rsh);
  }
  for (int i = 1; i <= len; i++) {
    ans[i] += ans[i - 1];
  }
  for (int x; q--; ) {
    cin >> x;
    cout << ans[min(x - 1, n - x)] << '\n';
  }
  return 0;
}